spring:
  application:
    name: EUREKA

eureka:
  instance:
    preferIpAddress: true
    lease-expiration-duration-in-seconds: 60

logging:
  config: classpath:logback.xml

---

spring:
  profiles: eureka1

server:
  port: 8761

eureka:
  instance:
    hostname: 192.168.1.156
  client:
    serviceUrl:
      defaultZone: http://192.168.1.103:8761/eureka/

---

spring:
  profiles: eureka2

server:
  port: 8761

eureka:
  instance:
    hostname: 192.168.1.103
  client:
    serviceUrl:
      defaultZone: http://192.168.1.156:8761/eureka/
