spring:
  application:
    name: TREE-DISCOVERY

eureka:
  instance:
    preferIpAddress: true
    lease-expiration-duration-in-seconds: 30
    hostname: 192.168.1.156
  client:
    serviceUrl:
      defaultZone: http://192.168.1.103:8761/eureka/

server:
  port: 8761

management:
  endpoints:
    web:
      exposure:
        include: info, health, metrics

logging:
  config: classpath:logback.xml

---

spring:
  profiles: eureka2

eureka:
  instance:
    hostname: 192.168.1.103
  client:
    serviceUrl:
      defaultZone: http://192.168.1.156:8761/eureka/
