spring:
  application:
    name: TREE-DISCOVERY

eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
    lease-expiration-duration-in-seconds: 60
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      # 'default-zone'으로 지정하면 안됨.
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

server:
  port: 8761

management:
  endpoints:
    web:
      exposure:
        include: info, health, metrics

logging:
  config: classpath:logback.xml
